name: Deploy to FTP Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /notes/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/**
          *.md
          *.log
        
    - name: Notify deployment success
      if: success()
      run: echo "✅ Deployment to /notes/ directory successful!"
      
    - name: Notify deployment failure
      if: failure()
      run: echo "❌ Deployment failed. Check logs for details."
